services:
  jmeter:
    container_name: jmeter
    build:
      context: ./jmeter
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./jmeter/tests-plans:/tests-plans
      - ./jmeter/scripts:/scripts
      - ./jmeter/reports:/reports
      - ./jmeter/data:/tests/data
    #entrypoint: ["/bin/bash", "/scripts/run-tests.sh"]
    entrypoint: ["tail", "-f", "/dev/null"] # subir o JMeter sem rodar os testes
    tty: true
    networks:
      - jmeter-net

  nginx:
    image: nginx:alpine
    container_name: jmeter-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./jmeter/reports:/usr/share/nginx/html/reports:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/auth:/etc/nginx/auth:ro
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - jmeter
    networks:
      - jmeter-net

  certbot:
    image: certbot/certbot
    container_name: jmeter-certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    command: >
      certonly --webroot
      --webroot-path=/var/www/certbot
      --email ${CERTBOT_EMAIL}
      --agree-tos
      --no-eff-email
      --non-interactive
      --force-renewal
      -d ${CERTBOT_DOMAIN}
    networks:
      - jmeter-net

networks:
  jmeter-net:
    driver: bridge
