version: "3.9"

services:
  jmeter:
    container_name: jmeter
    build:
      context: ./jmeter
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./jmeter/test-plans:/test-plans
      - ./jmeter/scripts:/scripts
      - ./jmeter/reports:/reports
      - ./jmeter/data:/tests/data
    entrypoint: ["/bin/bash", "/scripts/run-tests.sh"]
    #entrypoint: ["tail", "-f", "/dev/null"] #subri o JMeter sem rodas os testes automaticamente.
    tty: true
    networks:
      - jmeter-net

  nginx:
    image: nginx:alpine
    container_name: jmeter-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./jmeter/reports:/usr/share/nginx/html/reports:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/auth:/etc/nginx/auth:ro
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - jmeter
    networks:
      - jmeter-net

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    networks:
      - jmeter-net

networks:
  jmeter-net:
    driver: bridge
